export default {
    'AFC Academia': 'AFCA',
    'Argentina': 'ARG',
    'Atletico Madrid': 'ATL',
    'Blue Giants': 'BG',
    'Bravona': 'BV',
    'Brazil': 'BRA',
    'Caballeros de la Birra': 'LCB',
    'Caballeros De La Birra': 'LCB',
    'Chicago Me Limpio': 'CML',
    'Colchester United FC': 'CUFC',
    'Cold Chest FC': 'CCFC',
    'Defensores Del Bidon': 'CADB',
    'Defensores Del Doctor': 'CADD',
    'Deportivo Empate': 'UDE',
    'ECPG': 'ECPG',
    'Favela': 'FFC',
    'Galactic Boys': 'GB',
    'Jubilados': 'JUB',
    'Just Fragging': 'JF',
    'Just Fragging Academy': 'JFA',
    'Just Fragging B': 'JFB',
    'LA GALAXY': 'LAG',
    'LCB': 'LCB',
    'Layuve': 'LYV',
    'Los Halcones': 'LHFC',
    'MEIWA': 'MFC',
    'Meiwa': 'MFC',
    'Mateors Gaming': 'MG',
    'Meteors Gaming': 'MG',
    'Modo Diablo': 'MD',
    'Musashi FC': 'MCFC',
    'Nankatsu': 'NSC',
    'Painters United': 'PUFC',
    'Pelados Pretenciosos': 'PP',
    'Pfc': 'PUFC',
    'Pibes Chorros': 'PCS',
    'Pufc': 'PUFC',
    'Puro Humo': 'PH',
    'Real Mandril': 'RM',
    'STARGAZING FC': 'SGFC',
    'Santa Ana': 'SAFC',
    'Shaolin Soccer': 'SS',
    'Underdogs United': 'UDU',
    'United States': 'USA',
    'Uruguay': 'URU',
    'VIRAL TEAM': 'VRL',
    'Vorpal Swords': 'VS',
    'X-Squadron FC': 'XSN',
    'XSN': 'XSN',
    'Xoteiros': 'xT',
    'xT': 'xT'
}
